<a href="https://colab.research.google.com/github/DrLSimon/DL_lab_3AElec/blob/main/DL_lab_3AElec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

-------------------------
Tensors
==========================

Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to `NumPy’s <https://numpy.org/>`_ ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and
NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see `bridge-to-np-label`). Tensors
are also optimized for automatic differentiation (we'll see more about that later in the `Autograd <autogradqs_tutorial.html>`__
section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!


In [ ]:
import torch
import numpy as np

## Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`).



In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1352, 0.9956],
        [0.2678, 0.3374]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8536, 0.8259, 0.3275],
        [0.2959, 0.1651, 0.3099]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




## Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




## Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
indexing, slicing), sampling and more are
comprehensively described `here <https://pytorch.org/docs/stable/torch.html>`__.

Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

tensor = tensor.to(device) #same as tensor.to('cuda') or tensor.to('cpu')

Device tensor is stored on: cuda:0


Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.




**Standard numpy-like indexing and slicing:**



In [ ]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also `torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,
another tensor joining op that is subtly different from ``torch.cat``.



In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Arithmetic operations**



In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**Single-element tensors** If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using ``item()``:



In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


-------------------------
# Exercises on Tensor manipulation

## Exercise 1: 
Compute $\Vert t_1+t_2\Vert^2$ and return the result as a `float`. 
You should use `torch.square` and `torch.sum` in your solution.

<u>Hint:</u> Beware, that $t_1$ and $t_2$ have different shapes, so you should resize them to a common shape first.

In [80]:
debug = False # change to True for more unit test details
def exercise1(t1,t2):
  return 0.0

def test_exercise1():
  t1 = torch.ones((3,4))
  t2 = torch.arange(0,12)
  result = exercise1(t1,t2)
  expected = 386
  if isinstance(result, float) and result == expected:
    print('Exercise 1: OK')
  else:
    print('Exercise 1: NOK')
    if not isinstance(result, float):
      print('Hint: don\'t forget to return a float and not a tensor (with item())')
    if debug:
      print(f' result : {result}')
      print(f' expected : {expected}')

test_exercise1()

Exercise 1: NOK


## Exercice 2: Monte-carlo estimation of $\pi/4$
To estimate $\pi/4$, we can generate $n$ random samples in the unit square, and count the ratio that have a norm less than 1. To do so in pytorch, generate a random tensor of shape $n\times 2$ and compute the norm of each column, and guess the rest of the solution.
![Illustration](https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Pi_30K.gif/440px-Pi_30K.gif)


In [84]:
debug = False
def exercise2(n_samples):
  return torch.tensor([0.0]).double()
  
def test_exercise2():
  result = exercise2(int(1e7))
  expected = torch.tensor([torch.pi/4]).double()
  if  torch.isclose(result, expected, atol=1e-3):
    print('Exercise 2: OK')
  else:
    print('Exercise 2: NOK')
    if debug:
      print(f' result : {result.item()}')
      print(f' expected : {expected.item()}')

test_exercise2()

Exercise 2: NOK


# Training a Neural Network

## Linear regression from scratch

This material is adapted from from [this tutorial](https://colab.research.google.com/github/AyyappaSwamyPanthadi/JovianDLwithPyTorch/blob/main/02_linear_regression.ipynb).


### Quick recap on Linear Regression (You may skip this)



In this tutorial, we'll discuss one of the foundational algorithms in machine learning: *Linear regression*. We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall, and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

Visually, it means that the yield of apples is a linear or planar function of temperature, rainfall and humidity:

![linear-regression-graph](https://i.imgur.com/4DJ9f8X.png)

The *learning* part of linear regression is to figure out a set of weights `w11, w12,... w23, b1 & b2` using the training data, to make accurate predictions for new data. The _learned_ weights will be used to predict the yields for apples and oranges in a new region using the average temperature, rainfall, and humidity for that region. 

We'll _train_ our model by adjusting the weights slightly many times to make better predictions, using an optimization technique called *gradient descent*. Let's begin by importing Numpy and PyTorch.

### Training data

We can represent the training data using two matrices: `inputs` and `targets`, each with one row per observation, and one column per variable.

In [ ]:
# Input (temp, rainfall, humidity)
inputs_np = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [ ]:
# Targets (apples, oranges)
targets_np = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

We've separated the input and target variables because we'll operate on them separately. Also, we've created numpy arrays, because this is typically how you would work with training data: read some CSV files as numpy arrays, do some processing, and then convert them to PyTorch tensors.

Let's convert the arrays to PyTorch tensors.

In [ ]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs_np)
targets = torch.from_numpy(targets_np)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Prediction model and trainable parameters
The weights and biases (`w11, w12,... w23, b1 & b2`) can also be represented as matrices, initialized as random values. The first row of `w` and the first element of `b` are used to predict the first target variable, i.e., yield of apples, and similarly, the second for oranges.

In [ ]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.6060,  0.3331, -2.3709],
        [-0.8829, -0.5157,  0.5810]], requires_grad=True)
tensor([1.2229, 0.9915], requires_grad=True)


`torch.randn` creates a tensor with the given shape, with elements picked randomly from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 and standard deviation 1.

Our *model* is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).

![matrix-mult](https://i.imgur.com/WGXLFvA.png)

We can define the model as follows:

In [ ]:
def model(x):
    return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of a tensor.

The matrix obtained by passing the input data into the model is a set of predictions for the target variables.

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-195.6488,  -73.0255],
        [-267.3517,  -87.5452],
        [-231.3787, -111.2197],
        [-235.9925,  -89.7399],
        [-243.5801,  -68.7605]], grad_fn=<AddBackward0>)


Let's compare the predictions of our model with the actual targets.

In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


You can see a big difference between our model's predictions and the actual targets because we've initialized our model with random weights and biases. Obviously, we can't expect a randomly initialized model to *just work*.

### Loss function

Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets using the following method:

* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of all the elements in a tensor. The `.numel` method of a tensor returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.

In [ ]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(66108.5000, grad_fn=<DivBackward0>)


Here’s how we can interpret the result: *On average, each element in the prediction differs from the actual target by the square root of the loss*. And that’s pretty bad, considering the numbers we are trying to predict are themselves in the range 50–200. The result is called the *loss* because it indicates how bad the model is at predicting the target variables. It represents information loss in the model: the lower the loss, the better the model.

### Compute gradients with back-propagation

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases because they have `requires_grad` set to `True`. We'll see how this is useful in just a moment.

In [ ]:
# Compute gradients
loss.backward()

The gradients are stored in the `.grad` property of the respective tensors. Note that the derivative of the loss w.r.t. the weights matrix is itself a matrix with the same dimensions.

In [ ]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.6060,  0.3331, -2.3709],
        [-0.8829, -0.5157,  0.5810]], requires_grad=True)
tensor([[-26156.5156, -27766.3086, -17448.7422],
        [-14945.7070, -16474.9883, -10042.8691]])


### Adjust weights and biases to reduce the loss

In [ ]:
w
w.grad

tensor([[-26156.5156, -27766.3086, -17448.7422],
        [-14945.7070, -16474.9883, -10042.8691]])

In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

We multiply the gradients with a very small number (`10^-5` in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the *learning rate* of the algorithm. 

We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [ ]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(66108.5000, grad_fn=<DivBackward0>)


Before we proceed, we reset the gradients to zero by invoking the `.zero_()` method. We need to do this because PyTorch accumulates gradients. Otherwise, the next time we invoke `.backward` on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.

In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


### Train the model using gradient descent

As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm. Thus, we can _train_ the model using the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-150.4451,  -46.7566],
        [-207.9447,  -53.0173],
        [-161.2923,  -70.3138],
        [-190.9142,  -63.6934],
        [-186.6592,  -35.6002]], grad_fn=<AddBackward0>)


In [ ]:
# Calculate the loss
loss = mse(preds, targets)
loss_at_init = loss.item()
print(loss_at_init)

44663.7578125


In [ ]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-21490.7227, -22756.1406, -14356.1035],
        [-12233.0527, -13558.3418,  -8243.5039]])
tensor([-255.6511, -145.8763])


Let's update the weights and biases using the gradients computed above.

In [ ]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

Let's take a look at the new weights and biases.

In [ ]:
print(w)
print(b)

tensor([[-1.1295,  0.8383, -2.0529],
        [-0.6111, -0.2153,  0.7639]], requires_grad=True)
tensor([1.2285, 0.9947], requires_grad=True)


With the new weights and biases, the model should have a lower loss.

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
loss_after_update = loss.item()
print(f'Loss before update: {loss_at_init}')
print(f'Loss after  update: {loss_after_update}')

Loss before update: 44663.7578125
Loss after  update: 30211.916015625


We have already achieved a significant reduction in the loss merely by adjusting the weights and biases slightly using gradient descent.

### Train for multiple epochs

To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an _epoch_. Let's train the model for 100 epochs.

In [ ]:
def perform_one_update(inputs, targets, w, b):
    def model(inputs):
        return inputs @ w.t() +  b
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

def train_with_GD(inputs, targets, w, b, epochs=100):
    for epoch in range(epochs):
        perform_one_update(inputs, targets, w, b)
  
train_with_GD(inputs, targets, w, b, epochs=100)

Once again, let's verify that the loss is now lower:

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
loss_after_all_epochs_of_GD = loss.item()
print(f'Loss at init: {loss_at_init}')
print(f'Loss at the end: {loss_after_all_epochs_of_GD}')

Loss at init: 44663.7578125
Loss at the end: 239.5135955810547


The loss is now much lower than its initial value. Let's look at the model's predictions and compare them with the targets.

In [ ]:
# Predictions
preds

tensor([[ 57.7357,  72.1069],
        [ 66.6003, 103.8609],
        [153.2741, 122.8145],
        [ 21.5797,  46.6915],
        [ 74.7240, 119.2392]], grad_fn=<AddBackward0>)

In [ ]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

The predictions are now quite close to the target variables. We can get even better results by training for a few more epochs. 

## Exercice 3: Implement Linear regression with SGD (instead of full batch GD)


In [ ]:
#@title  New dataset
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
#@title Adapt the train_with_GD into train_with_SGD : you should observe that the SGD algorithm is more efficient than GD
def train_with_SGD(inputs, targets, w, b, epochs=100):
    raise Exception('Exercise 3: You should implement this function')
    

def run_method_and_return_loss(method, w0, b0):
    if method=='SGD':
      train_function = train_with_SGD
    else:
      train_function = train_with_GD
    w = w0.clone().requires_grad_()
    b = b0.clone().requires_grad_()
    def model(inputs):
        return inputs @ w.t() +  b
    with torch.no_grad():
        preds = model(inputs)
        loss_at_init = mse(preds, targets).item()
    # perform  for  100 epochs
    train_function(inputs, targets, w, b, epochs=100)
    with torch.no_grad():
        preds = model(inputs)
        loss_at_end = mse(preds, targets).item()
    return loss_at_init, loss_at_end

def test_exercise3():
    # init weights and biases
    w0 = torch.randn(2,3)
    b0 = torch.randn(2)
    loss_at_init, loss_at_end = run_method_and_return_loss('GD', w0, b0)
    print(f'Loss at init of  GD: {loss_at_init}')
    print(f'Loss after 100 epochs of GD: {loss_at_end}')
    loss_at_init, loss_at_end = run_method_and_return_loss('SGD', w0, b0)
    print(f'Loss at init of SGD: {loss_at_init}')
    print(f'Loss after 100 epochs of SGD: {loss_at_end}')

test_exercise3()
    

Loss at init of  GD: 49541.7578125
Loss after 100 epochs of GD: 214.45152282714844
Loss at init of SGD: 49541.7578125
Loss after 100 epochs of SGD: 1.1169384717941284


## Linear regression using PyTorch built-ins

We've implemented linear regression & gradient descent model using some basic tensor operations. However, since this is a common pattern in deep learning, PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.

Let's begin by importing the `torch.nn` package from PyTorch, which contains utility classes for building neural networks.

In [ ]:
import torch.nn as nn

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The `TensorDataset` allows us to access a small section of the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a `DataLoader`, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

We can use the data loader in a `for` loop. Let's look at an example.

In [ ]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 88., 134.,  59.],
        [103.,  43.,  36.],
        [ 92.,  87.,  64.],
        [ 91.,  87.,  65.],
        [ 73.,  66.,  44.]])
tensor([[118., 132.],
        [ 20.,  38.],
        [ 82., 100.],
        [ 80., 102.],
        [ 57.,  69.]])


In each iteration, the data loader returns one batch of data with the given batch size. If `shuffle` is set to `True`, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

### nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the `nn.Linear` class from PyTorch, which does it automatically.

In [ ]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3117, -0.0209, -0.1571],
        [-0.0426,  0.0636, -0.4653]], requires_grad=True)
Parameter containing:
tensor([ 0.1909, -0.5006], requires_grad=True)


PyTorch models also have a helpful `.parameters` method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [ ]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3117, -0.0209, -0.1571],
         [-0.0426,  0.0636, -0.4653]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1909, -0.5006], requires_grad=True)]

We can use the model to generate predictions in the same way as before.

In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 14.7909, -19.3537],
        [ 16.6639, -28.5551],
        [ 15.3963, -22.6671],
        [ 25.2764, -19.3234],
        [  8.6955, -29.9011],
        [ 15.1236, -19.4599],
        [ 16.5277, -29.0840],
        [ 15.5510, -23.1749],
        [ 24.9438, -19.2173],
        [  8.2267, -30.3238],
        [ 14.6547, -19.8826],
        [ 16.9965, -28.6613],
        [ 15.5325, -22.1382],
        [ 25.7453, -18.9007],
        [  8.3628, -29.7950]], grad_fn=<AddmmBackward0>)

### Loss Function

Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [ ]:
# Import nn.functional
import torch.nn.functional as F

The `nn.functional` package contains many useful loss functions and several other utilities. 

In [ ]:
# Define loss function
loss_fn = F.mse_loss

Let's compute the loss for the current predictions of our model.

In [ ]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(9982.5195, grad_fn=<MseLossBackward0>)


### Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for "stochastic gradient descent". The term _stochastic_ indicates that samples are selected in random batches instead of as a single group.

In [ ]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Note that `model.parameters()` is passed as an argument to `optim.SGD` so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate that controls the amount by which the parameters are modified.

### Train the model

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function `fit` that trains the model for a given number of epochs.

In [ ]:
# Utility function to train the model
def train_with_MiniBatchSGD(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update and `opt.zero_grad` to reset the gradients to zero.

* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. `loss.item` returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [ ]:
train_with_MiniBatchSGD(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 394.0146
Epoch [20/100], Loss: 36.3724
Epoch [30/100], Loss: 334.7254
Epoch [40/100], Loss: 258.8904
Epoch [50/100], Loss: 132.3746
Epoch [60/100], Loss: 107.4595
Epoch [70/100], Loss: 93.2856
Epoch [80/100], Loss: 84.1886
Epoch [90/100], Loss: 43.4242
Epoch [100/100], Loss: 51.9278


Let's generate predictions using our model and verify that they're close to our targets.

In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.5256,  71.6221],
        [ 79.7314,  95.9133],
        [120.0884, 140.5264],
        [ 30.0885,  45.4646],
        [ 92.5434, 105.9162],
        [ 57.4463,  70.5901],
        [ 79.1046,  95.1195],
        [120.1754, 140.6851],
        [ 31.1679,  46.4966],
        [ 92.9959, 106.1544],
        [ 57.8988,  70.8283],
        [ 78.6520,  94.8813],
        [120.7152, 141.3202],
        [ 29.6360,  45.2264],
        [ 93.6227, 106.9482]], grad_fn=<AddmmBackward0>)

In [ ]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

Indeed, the predictions are quite close to our targets. We have a trained a reasonably good model to predict crop yields for apples and oranges by looking at the average temperature, rainfall, and humidity in a region. We can use it to make predictions of crop yields for new regions by passing a batch containing a single row of input.

In [ ]:
with torch.no_grad():
    print(model(torch.tensor([[75, 63, 44.]])))

tensor([[54.8435, 67.7720]])


## Problem: Training an MLP classifier on FashionMNIST
FashionMNIST is a classification benchmark, where images are associated to classes. In this exercise, you shall have to adapt the linear regression to this context. The main adaptation steps are as follows:
* Change the dataset (using TorchVision)
* Replace the mere linear model by an MLP
* Change the MSE loss to a CrossEntropy loss


### Working with data
Remember that PyTorch has two `primitives to work with data <https://pytorch.org/docs/stable/data.html>`_:
``torch.utils.data.DataLoader`` and ``torch.utils.data.Dataset``.
``Dataset`` stores the samples and their corresponding labels, and ``DataLoader`` wraps an iterable around
the ``Dataset``.

PyTorch offers domain-specific libraries such as `TorchText <https://pytorch.org/text/stable/index.html>`_,
`TorchVision <https://pytorch.org/vision/stable/index.html>`_, and `TorchAudio <https://pytorch.org/audio/stable/index.html>`_,
all of which include datasets. For this tutorial, we  will be using a TorchVision dataset.

The ``torchvision.datasets`` module contains ``Dataset`` objects for many real-world vision data like
CIFAR, COCO (`full list here <https://pytorch.org/vision/stable/datasets.html>`_). In this tutorial, we
use the FashionMNIST dataset. 
Each training and test example is assigned to one of the following labels:

| Label | Description |
| --- | --- |
| 0 | T-shirt/top |
| 1 | Trouser |
| 2 | Pullover |
| 3 | Dress |
| 4 | Coat |
| 5 | Sandal |
| 6 | Shirt |
| 7 | Sneaker |
| 8 | Bag |
| 9 | Ankle boot |



Every TorchVision ``Dataset`` includes an argument: ``transform``
 to modify the samples.




In [ ]:
# Import TorchVision utilities
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose

# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

We pass the ``Dataset`` as an argument to ``DataLoader``. This wraps an iterable over our dataset, and supports
automatic batching, sampling, shuffling and multiprocess data loading. Here we define a batch size of 64, i.e. each element
in the dataloader iterable will return a batch of 64 features and labels.



In [ ]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

# Get one batch of data and print its tensor shape
X,y = iter(train_dataloader).next()
print("Shape of X [N, C, H, W]: ", X.shape)
print("Shape of y: ", y.shape, y.dtype)

Shape of X [N, C, H, W]:  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64


--------------




### Exercise 4: Creating  the MLP model

To define a MLP, you may rely on `nn.Sequential <https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html>`. It implements a sequential container modules made from a sequence of `nn.Module`. The goal here is to have the following sequence:

$$
I\in\mathbb R^{28}\otimes\mathbb R^{28}  
\xrightarrow{\mathrm{flatten}}{} \mathbb R^{28\times 28}=\mathbb R^{512}
\xrightarrow{\mathrm{Linear+ReLU}}{} \mathbb R^{512}
\xrightarrow{\mathrm{Linear+ReLU}}{} \mathbb R^{512}
\xrightarrow{\mathrm{Linear}}{} \mathbb R^{n_c}
$$

You shall implement this archticture, and determine what is the logical value for $n_c$ in our settings.

In [88]:
debug = True
def create_MLP():
    model = nn.Linear(512,512)
    return model

def test_exercise4():
    model = create_MLP()
    if not isinstance(model, nn.Sequential):
        print('Exercise 4: [NOK]')
        if debug:
            print(f'The model should be a nn.Sequential instance not {type(model)}')
        return

    if len(model) != 6:
        print('Exercise 4: [NOK]')
        if debug:
            print(f'The model should be 6 layers not {len(model)}')
        return
    
    model_device = next(model.parameters()).device
    expected_device = torch.empty(1).to(device).device
    if model_device != expected_device:
        print('Exercise 4: [NOK]')
        if debug:
            print(f'The model should run on {expected_device} not on {model_device}')
        return
    
    X,y = iter(train_dataloader).next()
    pred = model(X.to(device))
    expected_shape = torch.Size((batch_size, 10))
    if pred.shape != expected_shape:
        print('Exercise 4: [NOK]')
        if debug:
            print(f'The model predictions should be shaped as {expected_shape} not as {pred.shape}')
        return

    print('Exercise 4: [OK]')
    
    if debug:
        print(model)
  
test_exercise4()

Exercise 4: [NOK]
The model should be a nn.Sequential instance not <class 'torch.nn.modules.linear.Linear'>


--------------




### Exercise 5: Defining the loss function.
To train a model, we need a `loss function <https://pytorch.org/docs/stable/nn.html#loss-functions>`. 
The MSE loss is not the usually selected one for classification problems. You should propose a better suited loss.



In [89]:
def create_loss():
    loss_fn = nn.MSELoss()
    return loss_fn

def test_exercise5():
    loss_fn = create_loss()
    y = torch.arange(1,dtype=torch.long).to(device)
    pred = torch.ones((1,10),dtype=float).to(device)
    loss = loss_fn(pred, y).item()
    expected_loss = np.log(10) # entropy of a random [0-9] source
    if loss != expected_loss:
        print('Exercise 5: [NOK]')
        if debug:
            print(f'The loss should be {expected_loss} not as {loss}')
        return

    print('Exercise 5: [OK]') 

test_exercise5()


Exercise 5: [NOK]
The loss should be 2.302585092994046 not as 1.0


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


### Exercise 6: Performing the optimization
Getting inspired by the [Linear Regression example](#scrollTo=s4G-FSTAnTT8), complete the following function (single epoch) and launch the whole training procedure (remaining cells).


In [ ]:
def perform_one_epoch(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error and do the backpropagation and SGD step
        raise Exception('Exercise 6: You should implement this part of the algorithm')

        # Log the loss and progress
        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

We also check the model's performance against the test dataset to ensure it is learning.



In [ ]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

The training process is conducted over several iterations (*epochs*). During each epoch, the model learns
parameters to make better predictions. We print the model's accuracy and loss at each epoch; we'd like to see the
accuracy increase and the loss decrease with every epoch.



In [ ]:
epochs = 5
model = create_MLP()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
loss_fn = create_loss()
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    perform_one_epoch(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.303785  [    0/60000]
loss: 2.285972  [ 6400/60000]
loss: 2.264614  [12800/60000]
loss: 2.263567  [19200/60000]
loss: 2.244000  [25600/60000]
loss: 2.221651  [32000/60000]
loss: 2.235853  [38400/60000]
loss: 2.198303  [44800/60000]
loss: 2.199105  [51200/60000]
loss: 2.175558  [57600/60000]
Test Error: 
 Accuracy: 47.9%, Avg loss: 2.161790 

Epoch 2
-------------------------------
loss: 2.176006  [    0/60000]
loss: 2.156810  [ 6400/60000]
loss: 2.097935  [12800/60000]
loss: 2.118287  [19200/60000]
loss: 2.068115  [25600/60000]
loss: 2.015451  [32000/60000]
loss: 2.052073  [38400/60000]
loss: 1.966516  [44800/60000]
loss: 1.978436  [51200/60000]
loss: 1.912713  [57600/60000]
Test Error: 
 Accuracy: 56.8%, Avg loss: 1.900643 

Epoch 3
-------------------------------
loss: 1.936070  [    0/60000]
loss: 1.896961  [ 6400/60000]
loss: 1.775639  [12800/60000]
loss: 1.822379  [19200/60000]
loss: 1.716117  [25600/60000]
loss: 1.665387  [32000/600